- airbyte-local.sh
Remove latest version tag. This allows users to specif any version. IF the version is not specified, docker automatically will pull the latest anyways.
> Remove latest version tag

- airbyte-local.sh
By using tee to pipe stdout to multiple processes, removing the need to save source output to an intermediate file.
> Fix [#1]() 
> Use tee to process source output

- airbyte-local.sh
Airbyte sources write records to stdout, which docker treats as container logs. This change prevents docker from attempting to save extremely large container log files on the user's machine.
> Fix [#1]() 
> Set max docker container log size

- airbyte-local.sh
This makes it possible to specify a src/dst configuration via multiple (`--src.*/--dst.*`) args
E.g.,
```
--src.feed_cfg '{"feed_name":"buildkite-feed", "feed_path":"cicd/buildkite-feed"}'
```
is equivalent to:
```
--src.feed_cfg.feed_name 'buildkite-feed' \
--src.feed_cfg.feed_path 'cicd/buildkite-feed' 
```
> Fix #28 
> Ability to specify the src and dst configuration in multiple args

- airbyte-local.sh
- test/spec/airbyte-local_spec.sh
The current logic to write the destination config handles the Faros destination (`farosai/airbyte-faros-destination`) as a special case. We assume the Faros API URL, API key and graph to have been specified via `--dst.faros_api_url`,`--dst.faros_api_key` and `--dst.graph` respectively, and we use these values + `"edition": "cloud"` as the destination configuration.
This overwrites other values that might have been specified via `--dst.edition_configs` and is also Faros Cloud edition specific (doesn't support the Community Edition case).
This PR fixes the overwriting issue, while keeping the behavior that the special args (`--dst.faros_api_url`,`--dst.faros_api_key` and `--dst.graph`) are still included in the appropriate place in the configuration, for …
> Rework destination cfg to support both Faros editions

- README.md
- airbyte-local.sh
- test/spec/airbyte-local_spec.sh
Follow up to https://github.com/faros-ai/airbyte-local-cli/pull/44
We don't need Faros destination specific flags.
> Remove faros-destination specific logic

- airbyte-local.sh
`local -n` was introduced in Bash version 4.3 however we only enforce that Bash 4 be installed. This change supports passing associative arrays to functions in a Bash 4 supported way.
> Bash4 passing associative arrays

- airbyte-local.sh
> Warn user if bash < 4.3 and eval() is required

- airbyte-local.sh
- test/spec/airbyte-local_spec.sh
I get the following error if I use `--src-catalog-overrides` with my source:
```
[SRC]: 14:06:30 - {"type":"LOG","log":{"level":"FATAL","message":"2 validation errors for ConfiguredAirbyteCatalog\nstreams -> 0 -> stream -> supported_sync_modes\n  field required (type=value_error.missing)\nstreams -> 1 -> stream -> supported_sync_modes\n  field required (type=value_error.missing)\nTraceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 131, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 119, in run\n    config_catalog = …
```
> Include supported sync modes when overriding src catalog

- .gitignore
- README.md
- airbyte-local.sh
- test/spec/airbyte-local_spec.sh
Added optional `--output <path>` program option.  If specified, the destination container's `stdin` is `tee`'ed to the specified file.  This is very useful for capturing streams for debugging, etc.
> Add support for writing destination input to a file

- README.md
- airbyte-local.sh
- test/spec/airbyte-local_spec.sh
When using `--debug`, the secrets provided are output into the logs. They should be redacted. Which fields should be redacted is determined by which properties are `airbyte_secret` in the source/destination spec
> Redact secrets when debugging

- airbyte-local.sh
Added better help message and validation that `--src-output-file` is used in conjunction w/ a destination.
> Improve validation of arguments when using --src-output-file

- README.md
- airbyte-local.sh
We can now use `--src-wizard` and `--dst-wizard` to run the configuration wizard (provided the connectors implement it)
```
./airbyte-local.sh  \
--src 'farosai/airbyte-faros-feeds-source'  \
--src-wizard \
--dst 'farosai/airbyte-faros-destination' \
--dst-wizard
```
> Fix [#1]() 
> Add options to run the src/dst wizard

- airbyte-local.sh
Airbyte standardizes its community images on the "io.airbyte.version" label, and we follow that standard for our own images. I'm also logging the image digest, so for custom images that may not have that label, we can still pull and inspect the image.
> Fix [#1]() 
> FAI-6758 - Log connector image digests and io.airbyte.version labels

- airbyte-local.sh
Copy Faros API cfg from destination cfg to source cfg.
This is only done when the source is `farosai/airbyte-faros-feeds-source` and the destination is the Faros destination.
In this case, users of the CLI can omit Faros API config arguments from the source args. 
```
./airbyte-local.sh \
--src farosai/airbyte-faros-feeds-source:latest \
--src.feed_cfg.feed_name "github-feed" \
--src.feed_cfg.auth_cfg.auth "token" \
--src.feed_cfg.auth_cfg.personal_access_token $GH_TOKEN \
--src.feed_cfg.org_repo_list '["faros-ai/airbyte-connectors"]'  \
--src.feed_cfg.repos_query_mode.query_mode "FarosGraph" \
--dst farosai/airbyte-faros-destination:latest \
--dst.edition_configs.api_key $FAROS_API_KEY \
--dst.edition_configs.api_url "https://prod.api.faros.ai" \
--dst.edition_configs.graph "ypc-test" \ …
```
> FAI-7388 Copy Faros API cfg from destination cfg to source cfg + Make writeConfig more robust

- airbyte-local.sh
> Exclude state objects from destination output to reduce log size

- airbyte-local.sh
If a file exists whose name is exactly one letter where that letter is in one of the config paths to redact, bash replaces the path string with that letter when assigning the output of this [jq expression](https://github.com/faros-ai/airbyte-local-cli/blob/main/airbyte-local.sh#L400-L409) to an array variable. No idea why it does this.
> Fix [#1]() 
> FAI-8527 - Fix config redaction when one-letter filenames are present

- airbyte-local.sh
- test/spec/airbyte-local_spec.sh
1. Compact json rendering for updated config
2. Dont log unnecessary message when redirecting source output to /dev/null (default)
> Minor fixes

- airbyte-local.sh
> FAI-12311 - Don't overwrite state file with empty state

- .gitattributes
- airbyte-local.sh
Avoid having jq read files directly & fix file line endings. This comes to fix issues when running the CLI on Windows and git-bash
> Avoid having jq read files directly & fix file line endings 

- .github/workflows/ci.yaml
use shellspec cli instead of docker in github action.
this should allow us to easier run e2e tests that involving spinning up a docker container.
so that it's not much different of testing locally and running in github action.
I didn't touch the old one. keep the old one still using the shellspec docker.
> [FAI-14452] update ci to use shellspec cli

- airbyte-local-cli-nodejs/.gitignore
- airbyte-local-cli-nodejs/package-lock.json
- airbyte-local-cli-nodejs/package.json
- airbyte-local-cli-nodejs/src/command.ts
- airbyte-local-cli-nodejs/src/docker.ts
- airbyte-local-cli-nodejs/src/index.ts
- airbyte-local-cli-nodejs/src/utils.ts
- airbyte-local-cli-nodejs/test/__snapshots__/docker.it.test.ts.snap
- airbyte-local-cli-nodejs/test/__snapshots__/utils.it.test.ts.snap
- airbyte-local-cli-nodejs/test/command.test.ts
- airbyte-local-cli-nodejs/test/docker.it.test.ts
- airbyte-local-cli-nodejs/test/exec/spec/index_spec.sh
- airbyte-local-cli-nodejs/test/resources/test_config_file_src_only.json
- airbyte-local-cli-nodejs/test/resources/test_src_input
- airbyte-local-cli-nodejs/test/resources/test_src_input_invalid_json
- airbyte-local-cli-nodejs/test/utils.it.test.ts
> [FAI-14745] Process source airbyte connector output

- airbyte-local-cli-nodejs/src/utils.ts
- airbyte-local-cli-nodejs/test/utils.it.test.ts
- airbyte-local-cli-nodejs/test/utils.test.ts
Copy Faros API settings from destination config to source config.
This is for users' convenience so that they don't have to provide the same settings in both source and destination configs.
> Fix [#1]() 
> [FAI-14970] Copy faros api settings from dst to src config

- airbyte-local-cli-nodejs/src/docker.ts
- airbyte-local-cli-nodejs/src/types.ts
- airbyte-local-cli-nodejs/src/utils.ts
- airbyte-local-cli-nodejs/test/exec/spec/index_spec.sh
- airbyte-local-cli-nodejs/test/resources/test_config_file_dst_only.json.template
- airbyte-local-cli-nodejs/test/utils.it.test.ts
Users are not required to provide source config when it's dst only.
but they will be obligated to provide the corresponding catalog and dst stream with the correct prefix.
> [FAI-14970] Skip runnning discover catalog with dst only

- .github/workflows/ci.yaml
trying to fix this.
```
Download action repository 'sonarsource/sonarcloud-github-action@master' (SHA:f1700773ebdb6efe6b3f8a5cf66150027dda8f5e)
Getting action download info
Download action repository 'SonarSource/sonarqube-scan-action@v4.1.0' (SHA:1b442ee39ac3fa7c2acdd[41](https://github.com/faros-ai/airbyte-local-cli/actions/runs/13396689760/job/37420016350#step:1:47)0208dcb2bcfaae6c4)
Getting action download info
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v4.0.2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-too …
```
> Fix github action sonar scan version

- airbyte-local-cli-nodejs/package-lock.json
- airbyte-local-cli-nodejs/package.json
- airbyte-local-cli-nodejs/src/docker.ts
- airbyte-local-cli-nodejs/src/version.ts
- airbyte-local-cli-nodejs/test/__snapshots__/utils.it.test.ts.snap
- airbyte-local-cli-nodejs/test/docker.test.ts
- airbyte-local-cli-nodejs/test/resources/test_config_file.json
It looks like we need this for import sheets 
https://docs.faros.ai/docs/importing-org-data-from-a-local-spreadsheet#/
> [FAI-16250] Allow users to pass in additional docker volume mount

- README.md
This pull request updates the `README.md` file to improve its structure, readability, and clarity. The changes include refining headings, adding separators for better organization, and enhancing descriptions of configuration options.
* Improved the description of Docker configuration options for Airbyte connectors, including detailed explanations of `CPU`, `memory`, `log file size`, and the new `additionalOptions` field for advanced Docker settings. Also added an example for volume mounting using `HostConfig`.
* Removed redundant text about using the `--config-file` argument, simplifying the advanced user instructions.
> [FAI-16252] Add additional docker options instructions to Readme

- .gitattributes
- airbyte-local-cli-nodejs/test/__snapshots__/utils.it.test.ts.snap
- airbyte-local-cli-nodejs/test/resources/test_config_file_crlf.json
- airbyte-local-cli-nodejs/test/utils.it.test.ts
This pull request introduces support for parsing configuration files with CRLF line endings, adds a new test configuration file for CRLF, and updates related test cases and snapshots to ensure proper functionality. The changes primarily focus on enhancing the testing framework to handle different file encodings and line endings.
* Added a new test configuration file `test_config_file_crlf.json` with CRLF line endings to the repository for testing purposes
* Updated the `parseConfigFile` test suite to include a new test case for parsing CRLF-encoded files (`airbyte-local-cli-nodejs/test/utils.it.test.ts`).
> Add unit test for crlf

- airbyte-local-cli-nodejs/package-lock.json
This pull request updates several dependencies in `airbyte-local-cli-nodejs/package-lock.json` to newer versions, primarily focusing on the `brace-expansion` and `tar-fs` libraries. These updates improve security and compatibility by incorporating the latest changes from upstream.
Dependency updates:
* Updated `brace-expansion` from version `1.1.11` to `1.1.12` in multiple nested dependencies, including `@eslint/eslintrc`, `@humanwhocodes/config-array`, `eslint`, `glob`, `jake`, and `test-exclude` modules. [[1]](diffhunk://#diff-eda83e8c4f8f7ba146ee529af4db344b8e640cd31ffab00b37fa3e1a1e57ce95L1125-R1127) [[2]](diffhunk://#diff-eda83e8c4f8f7ba146ee529af4db344b8e640cd31ffab00b37fa3e1a1e57ce95L1269-R1271) [[3]](diffhunk://#diff-eda83e8c4f8f7ba146ee529af4db344b8e640cd31ffab00b37fa3e1a1e57ce95L …
> [FAI-16898] Vuln fix: tar-fs 

- airbyte-local-cli-nodejs/package-lock.json
- airbyte-local-cli-nodejs/package.json
- airbyte-local-cli-nodejs/src/constants/airbyteTypes.ts
- airbyte-local-cli-nodejs/src/version.ts
This pull request includes updates to the version of the `@faros-ai/airbyte-local-cli-nodejs` package and adds a new Airbyte source type. The most important changes include the version bump to `0.0.10`, the addition of the `cursor` Airbyte source, and the corresponding updates to version-related constants and metadata files.
* Updated the `version` field in `package.json` and `package-lock.json` to `0.0.10`, reflecting the new release version. (`[[1]](diffhunk://#diff-dd1fdd4ed8d30e34f5430be5f8169d15bcf36c6b45f4ca89a2e3f645a148add9L3-R3)`, `[[2]](diffhunk://#diff-eda83e8c4f8f7ba146ee529af4db344b8e640cd31ffab00b37fa3e1a1e57ce95L3-R9)`)
* Updated the `CLI_VERSION` constant in `src/version.ts` to `0.0.10`. (`[airbyte-local-cli-nodejs/src/version.tsL1-R1](diffhunk://#diff-2e15914795a909ef07261 …
> [FAI-17537] Add new source cursor

- airbyte-local-cli-nodejs/package-lock.json
- airbyte-local-cli-nodejs/package.json
- airbyte-local-cli-nodejs/src/command.ts
- airbyte-local-cli-nodejs/src/types.ts
- airbyte-local-cli-nodejs/src/utils.ts
- airbyte-local-cli-nodejs/src/version.ts
- airbyte-local-cli-nodejs/test/utils.test.ts
This pull request introduces support for overriding the destination stream prefix via a new CLI option, improves internal handling of the stream prefix, and updates relevant types and tests to accommodate this new functionality. The changes ensure that if a user provides a destination stream prefix using the CLI flag, it is respected and not overwritten by automatic generation logic.
**CLI Option and Input Handling:**
* Added a new hidden CLI option `--dst-stream-prefix <prefix>` to allow users to override the destination stream prefix, with conflict handling for the `connectionName` option.
* Updated the input parsing logic in `parseAndValidateInputs` to include the new `dstStreamPrefix` option in the configuration.
**Type Updates:**
* Added `dstStreamPrefix` to both `CliOptions` and …
> Add dst stream prefix flag

- airbyte-local-cli-nodejs/package-lock.json
- airbyte-local-cli-nodejs/package.json
- airbyte-local-cli-nodejs/src/docker.ts
- airbyte-local-cli-nodejs/src/utils.ts
- airbyte-local-cli-nodejs/src/version.ts
- airbyte-local-cli-nodejs/test/resources/test_config_file_src_only.json
This pull request updates the Docker image inspection and logging logic to be more robust against errors, and modifies a test resource configuration. The main improvements are better error handling when inspecting Docker images, safer logging of image details, and a test update to use a different image.
**Docker image inspection and error handling:**
* The `inspectDockerImage` function now returns an object with optional `digest` and `version` fields instead of always requiring them, allowing for cases where inspection fails.
* If inspecting a Docker image fails, the function logs a warning with the error message and returns an empty object, instead of throwing an error.
**Image version logging:**
* The `logImageVersion` function now checks for both `digest` and `version` before logging; …
> Update log image version to not fail on missing docker labels
