airbyte-local.sh

Support generic destination configs

---

airbyte-local.sh

Some QOL stuff:
- connection validation prior to running source
- source outputs to stdout and also is piped to destination
- source failures terminate processing

Connection validation & source failures

---

README.md
airbyte-local.sh

Readme example

---

README.md
airbyte-local.sh

Incremental state

---

README.md
airbyte-local.sh

Use discover command to generate catalog + allow user stream override

---

airbyte-local.sh

Also don't output records or state messages to terminal when piping to destination.
> Fix [#1]() 

Allow user to set origin and skip image pulls

---

airbyte-local.sh

Also output any logs generated by the `source discover` step to stdout.
> Fix [#1]() 

Allow user to specify destination stream prefix

---

airbyte-local.sh

Dont override user pref for state path

---

README.md
airbyte-local.sh

`--full-refresh` flag to set all streams to `full_refresh`
Top with `--full-refresh`, bottom without

`--full-refresh` flag

---

airbyte-local.sh

Pipe container log messages to stderr for visibility

---

README.md
airbyte-local.sh

Plus use same logging syntax as our events cli.
> Fix [#1]() 

Allow users to specify their own catalogs

---

README.md
airbyte-local.sh

Support any destination

---

README.md
airbyte-local.sh

Help, README, some reorganization to put logically similar things together.

--help & cleanup

---

airbyte-local.sh

Dont run destination logic if --src-only enabled ; kill containers if ctrl+c detected

---

.github/CODEOWNERS
airbyte-local.sh

> Fix [#23](https://github.com/faros-ai/airbyte-local-cli/issues/23) 

Color destination logs blue and add [src] [dst] prefixes

---

airbyte-local.sh

Added json_schema to source catalog + print catalog in debug

Added json_schema to source catalog + print catalog in debug

---

airbyte-local.sh

Unbuffer jq processes to output logs in real time and fix state naming

---

airbyte-local.sh

Add log timestamps

---

.github/workflows/ci.yaml
test/.shellspec
test/Dockerfile
test/spec/airbyte-local_spec.sh
test/spec/spec_helper.sh

FAI-2784 Adds tests for src/dst image validation and building the src cfg

---

.github/CODEOWNERS
airbyte-local.sh

Highlights + code owners

---

test/spec/airbyte-local_spec.sh

FAI-2784 Add tests around src catalog + src check + dst config functionality

---

README.md

Added CI badge + title

---

test/spec/airbyte-local_spec.sh

FAI-2784 Add dst catalog related test

---

README.md
airbyte-local.sh
test/spec/airbyte-local_spec.sh

Allow specifying memory for Docker containers

---

README.md
airbyte-local.sh

Allow setting max cpus + no default limit on mem & cpus + attach stdout/err/in

Allow setting max cpus + no default limit on mem & cpus + attach stdout/err/in

---

airbyte-local.sh

[Add option to keep containers after exit for debugging purposes](https://github.com/faros-ai/airbyte-local-cli/commit/2b92ab3e7a327f5936df3f43bc7cac503e902e4c)
[Add option to set airbyte container log level](https://github.com/faros-ai/airbyte-local-cli/commit/96befe6192db6392245aa651d8391a5a28f492f0)

More options

---

test/spec/airbyte-local_spec.sh

FAI-2784 Add stream prefix parsing tests

---

airbyte-local.sh

This is useful for instances where we want the destination to use the host network. For example, if we're running [Faros Community Edition](https://github.com/faros-ai/faros-community-edition/) and our Hasura instance is at `http://localhost:8080`, we need the destination to use the same network as the host, otherwise Hasura will be unreachable from within the destination.
More details on the Docker flag [here](https://docs.docker.com/network/network-tutorial-host/).
> Fix [#1]() 

Add option to use host network while running the destination

---

airbyte-local.sh

Allow overriding generated stream prefix

---

README.md
airbyte-local.sh

Add options to set docker run options

---

README.md

Added curl option

---

airbyte-local.sh

Temp path fixes for bash on Windows

Temp path fixes for bash on Windows

---

.github/workflows/ci.yaml
sonar-project.properties

Add Sonarcloud

---

airbyte-local.sh

Don't use colors in any output if --raw-messages is on

---

airbyte-local.sh

In addition to running state we should also proceed with execution when a container in the connection pod completed or got terminated

FAI-6548 - proceed with run if container terminated or completed

---

airbyte-local.sh
test/spec/airbyte-local_spec.sh

FAI-7276 - Ignore source image tag when creating stream prefix

---

airbyte-local.sh

Makes it possible to run `--src-wizard` / `--dst-wizard` with any Airbyte connector image (not just `farosai/*`) connectors.
> Fix [#1]() 

Support running the wizard on any Airbyte connector

---

airbyte-local.sh

This should help with typos and other such human error.
> Fix [#1]() 

Error when unrecognized argument detected

---

README.md

Added docs for docker-options argument

Added docs for docker-options argument

---

airbyte-local.sh

FAI-11873 - Return exit code from containers

---

airbyte-local.sh

FAI-11873 - Fix container cleanup when run with --src-only

---

airbyte-local-cli-nodejs/src/command.ts

Add command conflict for `dst-only`

---

airbyte-local-cli-nodejs/src/docker.ts
airbyte-local-cli-nodejs/src/index.ts
airbyte-local-cli-nodejs/src/types.ts
airbyte-local-cli-nodejs/src/utils.ts

[FAI-13687] Set up stream prefix and connection name

---

airbyte-local-cli-nodejs/src/command.ts
airbyte-local-cli-nodejs/src/docker.ts
airbyte-local-cli-nodejs/src/index.ts
airbyte-local-cli-nodejs/src/utils.ts
airbyte-local-cli-nodejs/test/command.test.ts
airbyte-local-cli-nodejs/test/docker.it.test.ts
airbyte-local-cli-nodejs/test/exec/spec/index_spec.sh
airbyte-local-cli-nodejs/test/utils.test.ts

Check list of what are tested
https://docs.google.com/document/d/17tUBnnudODTMGrJnsksIOfFNLG0oc8Q_u6HoN6VUEYw/edit?pli=1&tab=t.0#heading=h.t7ycoc16olsr

[FAI-14970] Fix cli command options bugs

---

airbyte-local-cli-nodejs/package-lock.json
airbyte-local-cli-nodejs/package.json
airbyte-local-cli-nodejs/src/version.ts

checking if the release works. 
the last one didn't work because the CI setup failed

Bump up version to release

---

.github/workflows/ci.yaml
airbyte-local-cli-nodejs/package-lock.json
airbyte-local-cli-nodejs/package.json
airbyte-local-cli-nodejs/src/docker.ts
airbyte-local-cli-nodejs/src/version.ts
airbyte-local-cli-nodejs/test/exec/spec/index_spec.sh

[FAI-15029] Add e2e tests and run in CI

---

.github/workflows/ci.yaml
airbyte-local-cli-nodejs/package-lock.json
airbyte-local-cli-nodejs/package.json
airbyte-local-cli-nodejs/src/version.ts

Fix ci release dependency

---

airbyte-local-cli-nodejs/package-lock.json
airbyte-local-cli-nodejs/package.json
airbyte-local-cli-nodejs/src/docker.ts
airbyte-local-cli-nodejs/src/index.ts
airbyte-local-cli-nodejs/src/utils.ts
airbyte-local-cli-nodejs/src/version.ts
airbyte-local-cli-nodejs/test/docker.it.test.ts
airbyte-local-cli-nodejs/test/exec/spec/index_spec.sh
airbyte-local-cli-nodejs/test/index.test.ts
airbyte-local-cli-nodejs/test/utils.test.ts

- fix docker cpu/mem settings: am i losing my mind? i thought i handled this. 
- fix underscore of dst stream prefix
- update pino to show error/warn/debug logs from source and destination container logs
- add more unit tests for main function

Fix docker cpu memory unit

---

airbyte-local-cli-nodejs/src/docker.ts

It seems like a bug from dockerode that the stdin attach will echo back the json payload of the stream settings.
Tried a bunch of workarounds (including the ones that chatgpt suggested), this is the only one works.
https://github.com/apocas/dockerode/issues/742
I ran it locally a few dozen times and wasn't able to prove this fixes the issue since it's not consistent and happens rarely. (but still happens). we will see if we encounter the issue again

[FAI-15333] workaround for dockerode stdin attach

---

airbyte-local-cli-nodejs/README.md

Fix   airbyte-local-cli-nodejs Readme

---

airbyte-local-cli-nodejs/src/constants/airbyteConfig.ts
airbyte-local-cli-nodejs/src/utils.ts
airbyte-local-cli-nodejs/test/__snapshots__/utils.it.test.ts.snap
airbyte-local-cli-nodejs/test/exec/spec/index_spec.sh
airbyte-local-cli-nodejs/test/utils.it.test.ts

[FAI-15789] Add static sample Airbyte configs

---

.gitattributes
.github/workflows/ci.yaml
README.md
airbyte-local-cli-nodejs/package-lock.json
airbyte-local-cli-nodejs/package.json
airbyte-local-cli-nodejs/src/version.ts

tested on the branch
For user convenience. they don't have to check for the latest version number

Publish latest release

---

.github/workflows/ci.yaml

Fix publish latest tag
